#!/bin/bash

echo "📧 Deploying send-email-hook Edge Function to Supabase"
echo ""

# Check if we're logged in (using npx supabase)
PROJECT_ID="gadedbrnqzpfqtsdfzcg"

echo "Project ID: $PROJECT_ID"
echo "Function: send-email-hook"
echo ""

# Deploy the function using the Supabase API
echo "🚀 Deploying using Supabase Management API..."
echo ""
echo "⚠️  IMPORTANT: To deploy Edge Functions, you need to:"
echo ""
echo "Option 1: Deploy via Supabase Dashboard"
echo "  1. Go to: https://supabase.com/dashboard/project/$PROJECT_ID/functions"
echo "  2. Click 'Deploy new function'"
echo "  3. Select 'send-email-hook' from your local files"
echo "  4. Or use the web editor to create it"
echo ""
echo "Option 2: Use Supabase CLI (requires installation)"
echo "  # Install Supabase CLI"
echo "  brew install supabase/tap/supabase  # macOS"
echo "  # or"
echo "  npm install -g supabase  # This doesn't work globally"
echo "  # or"
echo "  curl -fsSL https://supabase.com/install.sh | sh  # Linux"
echo ""
echo "  # Login"
echo "  supabase login"
echo ""
echo "  # Link project"
echo "  supabase link --project-ref $PROJECT_ID"
echo ""
echo "  # Deploy function"
echo "  supabase functions deploy send-email-hook"
echo ""
echo "Option 3: Deploy via GitHub Actions (recommended for production)"
echo "  - Set up GitHub Actions workflow"
echo "  - Automatic deployment on push to main branch"
echo ""
echo "📋 Function File Location:"
echo "  /workspaces/videoremix.vip2/supabase/functions/send-email-hook/index.ts"
echo ""
echo "🔧 After Deployment:"
echo "  1. Enable the 'Send Email' hook in Supabase Dashboard"
echo "  2. Go to: https://supabase.com/dashboard/project/$PROJECT_ID/auth/hooks"
echo "  3. Enable 'Send Email' hook"
echo "  4. Set URL: https://$PROJECT_ID.supabase.co/functions/v1/send-email-hook"
echo "  5. Click Save"
echo ""
