services:
  - type: web
    name: maigret-worker
    env: python
    rootDir: maigret-worker
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MAIGRET_WORKER_SECRET
        generateValue: true