-- ============================================================
-- RAG Tutorials conversion: pgvector setup for Supabase
-- ============================================================
-- This migration creates:
--  1. pgvector extension
--  2. match_documents(vector_query, vector_embedding, match_threshold, match_count)
--     Similarity search RPC returning documents with metadata
-- ============================================================

-- Enable the pgvector extension
create extension if not exists vector;

-- ============================================================
-- Function: match_documents(vector, integer, float)
-- ============================================================
-- Searches the 'documents' table (created by Supabase pgvector plugin)
-- returning the k most similar documents with similarity score.
--
-- Parameters:
--   query_embedding  - vector (1536 dimensions expected)
--   match_threshold  - minimum cosine similarity (default 0.0)
--   match_count      - maximum number of documents to return (default 5)
--
-- Returns: id, content, metadata, similarity (1 - distance)
-- ============================================================

create or replace function match_documents (
  query_embedding vector(1536),
  match_threshold float default 0.0,
  match_count int default 5
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language sql stable
as $$
  select
    documents.id,
    documents.content,
    documents.metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where 1 - (documents.embedding <=> query_embedding) > match_threshold
  order by documents.embedding <=> query_embedding
  limit match_count;
$$;

comment on function match_documents(vector, float, int) is
  'Vector similarity search over stored document embeddings. '
  ||'Returns the k-nearest neighbours with cosine similarity scores. '
  ||'Requires the pgvector extension and documents table with embedding column.';

-- ============================================================
-- Collections table to track multiple RAG collections (apps)
-- ============================================================
create table if not exists rag_collections (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  description text,
  embedding_model text not null default 'text-embedding-3-small',
  vector_size integer not null default 1536,
  distance_metric text not null default 'cosine',
  search_k integer not null default 5,
  score_threshold float not null default 0.0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table rag_collections enable row level security;

-- Indexes
create index if not exists idx_rag_collections_slug on rag_collections(slug);
create index if not exists idx_documents_embedding on documents using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);  -- tune based on dataset size

-- ============================================================
-- Enable vector extension on documents (safety)
-- ============================================================
-- The Supabase 'documents' table from pgvector extension has:
--   id, content, metadata (jsonb), embedding (vector)
-- Ensure the embedding column is configured for 1536-d OpenAI embeddings

-- ============================================================
-- Helper: upsert collection record
-- ============================================================
create or replace function upsert_rag_collection(
  p_slug text,
  p_name text,
  p_description text default null,
  p_embedding_model text default 'text-embedding-3-small',
  p_vector_size integer default 1536,
  p_distance_metric text default 'cosine',
  p_search_k integer default 5,
  p_score_threshold float default 0.0
)
returns jsonb
language plpgsql
as $$
declare
  v_id bigint;
begin
  insert into rag_collections
    (slug, name, description, embedding_model, vector_size, distance_metric, search_k, score_threshold)
  values
    (p_slug, p_name, p_description, p_embedding_model, p_vector_size, p_distance_metric, p_search_k, p_score_threshold)
  on conflict (slug) do update set
    name = excluded.name,
    description = excluded.description,
    embedding_model = excluded.embedding_model,
    vector_size = excluded.vector_size,
    distance_metric = excluded.distance_metric,
    search_k = excluded.search_k,
    score_threshold = excluded.score_threshold,
    updated_at = timezone('utc'::text, now())
  returning id into v_id;

  return jsonb_build_object(
    'id', v_id,
    'slug', p_slug,
    'action', case when pg_last_notice() is null then 'inserted' else 'updated' end
  );
end;
$$;

-- ============================================================
-- RPC: get_rag_collection(slug)
-- ============================================================
create or replace function get_rag_collection(p_slug text)
returns jsonb
language sql stable
as $$
  select to_jsonb(rag_collections.*) from rag_collections
  where slug = p_slug
  limit 1;
$$;

-- ============================================================
-- RPC: list_rag_collections()
-- ============================================================
create or replace function list_rag_collections()
returns jsonb
language sql stable
as $$
  select jsonb_agg(to_jsonb(rag_collections))
  from rag_collections
  order by created_at desc;
$$;

-- ============================================================
-- RLS Policies for rag_collections (service role bypasses)
-- ============================================================
create policy "Allow public read for rag_collections"
  on rag_collections for select
  using (true);

create policy "Allow service role full access"
  on rag_collections for all
  using (auth.role() = 'service_role');

-- ============================================================
-- Seed: Register RAG tutorials collections
-- ============================================================
insert into rag_collections (slug, name, description, embedding_model, vector_size, search_k, score_threshold)
values
  ('rag-database-routing', 'RAG Database Routing', 'Multi-collection routing (products/support/finance) with vector similarity fallback + LLM router', 'text-embedding-3-small', 1536, 5, 0.5),
  ('gemini-agentic-rag', 'Gemini Agentic RAG', 'Agentic RAG with query rewriting, Exa web fallback, and Gemini 2.0 agent', 'text-embedding-3-small', 1536, 5, 0.7),
  ('deepseek-local-rag-agent', 'DeepSeek Local RAG Agent', 'Local LLM RAG Agent via OpenAI GPT-4o; originally Ollama/DeepSeek', 'text-embedding-3-small', 1536, 5, 0.7),
  ('ai-blog-search', 'AI Blog Search', 'LangGraph Agentic RAG for LLM blog posts', 'text-embedding-3-small', 1536, 5, 0.0),
  ('rag-chain-pharma', 'RAG Chain PharmaQuery', 'Simple pharmaceutical RAG chain - sentence transformers', 'text-embedding-3-small', 1536, 5, 0.0),
  ('autonomous-rag', 'AutoRAG', 'Autonomous RAG agent with storage and web search (Agno)', 'text-embedding-3-small', 1536, 3, 0.0),
  ('agentic-rag-embedding-gemma', 'Agentic RAG EmbeddingGemma', 'Local EmbeddingGemma + Llama3 - converted to OpenAI', 'text-embedding-3-small', 1536, 5, 0.7),
  ('agentic-rag-with-reasoning', 'Agentic RAG with Reasoning', 'Step-by-step reasoning with Gemini via OpenAI GPT-4o', 'text-embedding-3-small', 1536, 5, 0.7),
  ('qwen-local-rag', 'Qwen Local RAG', 'Local Qwen RAG via OpenAI GPT-4o', 'text-embedding-3-small', 1536, 5, 0.7),
  ('agentic-rag-gpt5', 'Agentic RAG GPT-5', 'Agentic RAG with GPT-5 (mapped to GPT-4o)', 'text-embedding-3-small', 1536, 5, 0.7),
  ('knowledge-graph-rag-citations', 'Knowledge Graph RAG Citations', 'Manual review: Neo4j knowledge graph'),
  ('contextual-ai-rag-agent', 'Contextual AI RAG Agent', 'Manual review: Contextual AI SaaS'),
  ('vision-rag', 'Vision RAG', 'Manual review: multimodal image RAG'),
  ('llama31-local-rag', 'Llama3.1 Local RAG', 'Webpage RAG with Llama3.1 local; converted to OpenAI embeddings', 'text-embedding-3-small', 1536, 5, 0.0),
  ('local-hybrid-search-rag', 'Local Hybrid Search RAG', 'Manual review: RAGLite hybrid vector+BM25'),
  ('rag-agent-cohere', 'RAG Agent Cohere', 'Cohere Emb v3 + CmdR+ with compressed vectors', 'text-embedding-3-small', 1536, 10, 0.7),
  ('corrective-rag', 'Corrective RAG', 'Corrective RAG with LangGraph document grading + Tavily', 'text-embedding-3-small', 1536, 5, 0.7),
  ('rag-as-a-service', 'RAG-as-a-Service', 'RAGie-based RaaS - Manual review (external SaaS)', null, null, null, null),
  ('hybrid-search-rag', 'Hybrid Search RAG', 'Manual review: RAGLite with Cohere reranker'),
  ('agentic-rag-math-agent', 'Agentic RAG Math Agent', 'Manual review: DSPy guardrails + LlamaIndex math RAG')
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description;
-- ============================================================
-- End RAG Tutorials migration
-- ============================================================
