/**
 * The 100 AI-powered apps that run as first-party experiences
 * inside the VideoRemix dashboard (React + Supabase Edge Functions).
 *
 * These are distinct from the 15 legacy apps that have their own
 * individual Netlify deployments (with videoremix.vip custom domains).
 */
export const INTERNAL_AI_APP_SLUGS = new Set([
  "ai-sales-intelligence-pro",
  "lead-research-scraper-ai",
  "ai-business-growth-consultant",
  "ai-strategy-advisor",
  "ai-sales-email-writer",
  "ai-offer-decision-helper",
  "launch-campaign-builder-ai",
  "competitor-spy-ai",
  "ai-agency-builder-suite",
  "sales-call-follow-up-ai",
  "blog-to-podcast-ai",
  "daily-content-engine-ai",
  "ai-content-creator-pro",
  "ai-content-editor",
  "ai-documentation-writer",
  "youtube-repurposer-ai",
  "newsletter-repurposer-ai",
  "ai-news-content-writer",
  "ai-video-script-producer",
  "ai-music-idea-generator",
  "ai-film-producer",
  "podcast-creator-ai",
  "news-to-podcast-ai",
  "ai-voice-support-agent",
  "talk-to-your-business-ai",
  "ai-audio-guide-creator",
  "ai-intake-voice-agent",
  "ai-dictation-assistant",
  "ai-music-jingle-assistant",
  "business-knowledgebase-ai",
  "pdf-business-assistant",
  "research-paper-assistant",
  "codebase-chat-ai",
  "gmail-intelligence-ai",
  "video-knowledge-assistant",
  "blog-knowledge-search-ai",
  "visual-document-ai",
  "citation-knowledgebase-ai",
  "smart-search-ai",
  "private-company-ai-assistant",
  "multimodal-knowledge-ai",
  "ai-knowledgebase-debugger",
  "real-estate-marketing-ai",
  "home-renovation-visualizer-ai",
  "travel-planner-ai",
  "local-tour-guide-ai",
  "local-business-voice-assistant",
  "local-business-growth-advisor",
  "local-business-analytics-ai",
  "ai-hiring-assistant",
  "resume-analyzer-ai",
  "candidate-decision-ai",
  "candidate-outreach-ai",
  "interview-summary-ai",
  "hiring-plan-builder",
  "finance-research-ai",
  "business-finance-ai-team",
  "profit-coach-ai",
  "investment-research-assistant",
  "startup-due-diligence-ai",
  "revenue-data-analyst-ai",
  "financial-dashboard-ai",
  "contract-summary-ai",
  "legal-pdf-explainer",
  "policy-compliance-assistant",
  "claim-checker-ai",
  "fraud-investigation-assistant",
  "risk-decision-ai",
  "ai-app-builder-assistant",
  "ai-saas-architect",
  "ai-code-review-pro",
  "ai-bug-fixer",
  "ai-fullstack-builder",
  "python-fixer-ai",
  "github-repo-assistant",
  "github-automation-agent",
  "build-plan-generator",
  "sprint-planner-ai",
  "ai-design-studio",
  "landing-page-critic-ai",
  "ai-ux-designer",
  "dashboard-designer-ai",
  "landing-page-copy-ai",
  "conversion-copy-editor",
  "research-assistant-ai",
  "deep-research-pro",
  "research-planner-ai",
  "ai-course-creator-assistant",
  "academic-research-ai",
  "market-research-ai",
  "fact-check-ai",
  "research-memory-assistant",
  "personal-ai-memory-assistant",
  "multi-ai-memory-hub",
  "private-ai-chat-with-memory",
  "private-chatgpt-clone",
  // Overflow apps (built with existing tool types)
  "travel-concierge-ai",
  "email-memory-assistant",
  "browser-task-agent",
  "ai-tool-router",
]);

/**
 * Note: notion-workspace-ai is intentionally NOT in this list
 * because it requires Notion API integration which is not currently available.
 */

export function isInternalAIApp(slug: string): boolean {
  return INTERNAL_AI_APP_SLUGS.has(slug);
}
