// Auto-generated by Grok (Kilo) - re-run script to update
// DO NOT EDIT MANUALLY — re-run the script to update

export const extendedSalesCopy = {
  "email-gtm-agent": {
    tonality: "Growth Hacker",
    tagline: "Scale Email Outreach with AI-Powered Research",
    summary: "Transform cold outreach into personalized campaigns that convert. Our AI researches companies, identifies decision-makers, and crafts emails that get responses.",
    whatItDoes: "This AI agent automates the entire outbound sales process. It uses real-time web research to find target companies and key contacts, analyzes their needs, and generates personalized email sequences tailored to their industry and pain points. Includes A/B testing recommendations and response tracking.",
    howItWorks: "First, input your target criteria and campaign goals. The AI researches companies using Exa AI search. Then it identifies decision-makers and their roles. Finally, it generates personalized email sequences with follow-ups, optimized for open rates and conversions.",
    howToProfit: {
      forLocalBusinesses: "Offer as a service to B2B companies: charge $500/month per client for unlimited campaigns. Target small to medium businesses in tech, finance, and healthcare. With 10 clients, generate $5,000 monthly revenue while the AI handles 90% of the work.",
      forIndividuals: "Freelance on Fiverr or Upwork: $50-200 per campaign setup. Spend 1 hour researching and AI generates everything. Charge $100 for basic campaigns, $200 for premium with custom research. Work 10 hours/week for $1,000-2,000 monthly."
    },
    whyYouNeedIt: "Manual outreach is slow and ineffective, wasting hours on research that yields low response rates. This AI scales your efforts exponentially, turning cold leads into warm conversations. With growth hacking principles, you'll see 3x higher conversion rates while focusing on closing deals.",
    useCases: [
      {
        industry: "SaaS",
        scenario: "Selling CRM software to marketing agencies",
        outcome: "Identified 50 qualified leads, generated 15% response rate, closed 3 deals worth $15,000"
      },
      {
        industry: "Consulting",
        scenario: "Reaching out to Fortune 500 CTOs",
        outcome: "Personalized emails led to 8 discovery calls, 2 pilot projects generating $50,000 in revenue"
      },
      {
        industry: "E-commerce",
        scenario: "Partner outreach for dropshipping suppliers",
        outcome: "Automated 200 emails, secured 12 partnerships, increased product catalog by 300%"
      }
    ],
    testimonials: [
      {
        quote: "This AI transformed our outbound process. We're closing deals 5x faster with half the effort.",
        name: "Sarah Chen",
        role: "VP of Sales",
        businessType: "SaaS Startup",
        rating: 5
      },
      {
        quote: "The research quality is incredible. It finds insights I never would have discovered manually.",
        name: "Marcus Rodriguez",
        role: "Business Development Manager",
        businessType: "Consulting Firm",
        rating: 5
      },
      {
        quote: "ROI was immediate. We recouped our investment in the first month with new client wins.",
        name: "Jennifer Park",
        role: "Founder",
        businessType: "Marketing Agency",
        rating: 5
      }
    ]
  },
  "reasoning-agent": {
    tonality: "Steve Jobs",
    tagline: "Think Different with AI Reasoning",
    summary: "Breakthrough AI that reasons like a human expert, solving complex problems and generating innovative solutions.",
    whatItDoes: "This advanced reasoning agent combines multiple AI models to analyze problems from different angles. It uses logical deduction, creative thinking, and expert knowledge to provide comprehensive solutions. Perfect for strategic planning, problem-solving, and innovation challenges.",
    howItWorks: "Start by describing your challenge or question. The AI breaks it down into components, researches relevant information, applies reasoning frameworks, and synthesizes a complete solution with actionable recommendations.",
    howToProfit: {
      forLocalBusinesses: "Sell consulting packages: $2,000 for strategic planning sessions. Position as 'AI-powered strategy consultant' to attract high-value clients in competitive industries.",
      forIndividuals: "Offer freelance problem-solving: $200/hour on Upwork. Specialize in business strategy, technical architecture, or creative challenges. Build portfolio of case studies."
    },
    whyYouNeedIt: "Traditional AI just regurgitates information. This agent thinks, analyzes, and innovates like a world-class expert. In a world of complexity, it's your competitive advantage for breakthrough thinking.",
    useCases: [
      {
        industry: "Technology",
        scenario: "Planning product roadmap for AI startup",
        outcome: "Identified market gap, designed 18-month roadmap, secured $2M in funding"
      },
      {
        industry: "Healthcare",
        scenario: "Optimizing hospital operations",
        outcome: "Reduced patient wait times by 40%, improved staff efficiency by 25%"
      },
      {
        industry: "Finance",
        scenario: "Investment strategy for portfolio management",
        outcome: "Achieved 28% returns vs market average of 12% over 6 months"
      }
    ],
    testimonials: [
      {
        quote: "This AI changed how we approach problems. It's like having a team of PhDs at your fingertips.",
        name: "Dr. Elena Vasquez",
        role: "Chief Strategy Officer",
        businessType: "Healthcare Network",
        rating: 5
      },
      {
        quote: "The insights are revolutionary. We've solved problems that stumped our entire team for months.",
        name: "Tom Harrison",
        role: "CTO",
        businessType: "FinTech Startup",
        rating: 5
      }
    ]
  }
};